PalletTown_RivalsHouse_Text_HiBrothersAtLab::
    .string "TANSI: Kwe', {PLAYER}!\p"
    .string "Uksisl {RIVAL} emittukwatk\n"
    .string "NMIJKA KINA'MUO'KUOM.$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
    .string "TANSI: {PLAYER}, nutmai\n"
    .string "ki'l matnk {RIVAL}.\p"
    .string "Na'jikai nemitu wla!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
    .string "NMIJKA etamatl ki'l\n"
    .string "elukowatl?\p"
    .string "Ji, malo'pj.\n"
    .string "Iknmul wetmo'taqan.$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
    .string "{PLAYER} mesn'k KJIKANN L'SK'J.\n"
    .string "Wela'lin TANSI!$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
    .string "Ki'lewei MUNTI' wajueknepit.$"

PalletTown_RivalsHouse_Text_ExplainTownMap::
    .string "Ankapt'k KJIKANN L'SK'J\n"
    .string "we'jitoq pilei kjikann, kisna\l"
    .string "kekina'masit kjikann wisunn.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
    .string "TANSI: Nkutei l'nu,\n"
    .string "POKéMON nimajit.\p"
    .string "Ta'n nekmow kispniet,\n"
    .string "atlasmu'latl.$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
    .string "Meski'k l'sk'j KANTO um'tki.\n"
    .string "Uktapsunik!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
	.string "Wajuiknetek POKéMON\n"
	.string "kekina'matimkewei.$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
    .string "TANSI: Kwe', {PLAYER}!\n"
    .string "Naqsipkisink.\p"
    .string "Wikumul, epa'sit.\p"
    .string "O, katu, kilewewei\n"
    .string "POKéMON emekwamuksit.\p"
    .string "Pewalit pankwenatl newt?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
    .string "Mutt pankwenk?\n"
    .string "Oke', p'teweie'maiek.$"

PalletTown_RivalsHouse_Text_GroomWhichOne::
    .string "Teken newt pankwenk?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
    .string "TANSI: Oke', ne'tma'sit!\n"
    .string "Jaqalilukwet!$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
#ifdef BUGFIX @ The localizers missed what should be a textcolor change in the localizations.
    .string "{COLOR DARK_GRAY}{STR_VAR_1} jajikamuksit…\p"
    .string "{COLOR RED}TANSI: Ala! Kaqalukwei.\n"
#else @ In the JP games, gender-based text used a different font instead of different colors.
    .string "{FONT_NORMAL}{STR_VAR_1} jajikamuksit…\p"
    .string "{FONT_FEMALE}TANSI: Ala! Kaqalukwei.\n"
#endif
    .string "Wikwasamu'k?\p"
    .string "Weskewei…\n"
    .string "Wikwasamuksit POKéMON.$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
    .string "O, meskei'. Mutt pakwenk\n"
    .string "WA'W, melujioqo.$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
    .string "TANSI: Kilewewei POKéMON kesalatl\n"
    .string "Ta'n tlipkije'k ankweiwatl kesalatl.\p"
    .string "For example, {PLAYER}, may I see\n"
    .string "your first POKéMON?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
    .string "Kesalatl ki'l piamiw me' wen!\p"
    .string "Ki'lewei mawiulta'sit.$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
    .string "Weljesink.\p"
    .string "Na'jikai {RIVAL} nemitu aq\n"
    .string "kekina'masit.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly::
    .string "Ni'laje'k.\n"
    .string "Siawa'sit na kelu'lk!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
    .string "Apu'jenatl.\n"
    .string "Pujite'lmatl.$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
    .string "Mnaq nenuatl ki'l\p"
    .string "POKéMON ms't metuie'tk\n"
    .string "ta'n ki'l mesnatl.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
    .string "{PLAYER}, Mutt gesatm…\n"
    .string "Winikwetutk.\p"
    .string "Kina'sit uleiatimkewei.$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
    .string "…O, mutt o'plapukuet…\n"
    .string "Koqwei ukjit ki'lewei\n"
    .string "POKéMON maskelmatl te'sit?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
    .string "“Esmatmuksit aq sekkw\n"
    .string "CLEFAIRY”$"

