PalletTown_RivalsHouse_Text_HiBrothersAtLab::
    .string "DAISY: Kwe', {PLAYER}!\p"
    .string "Uksisl {RIVAL} emittukwatk\n"
    .string "NMIJKA KINA'MUO'KUOM.$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
    .string "DAISY: {PLAYER}, nutmai\n"
    .string "ki'l matnk {RIVAL}.\p"
    .string "Na'jikai nemitu wla!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
    .string "NMIJKA etamatl ki'l\n"
    .string "elukowatl?\p"
    .string "Ji, malo'pj.\n"
    .string "Iknmul wetmo'taqan.$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
    .string "{PLAYER} mesn'k KJIKANN L'SK'J.\n"
    .string "Wela'lin DAISY!$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
    .string "Ki'lewei MUNTI' wajueknepit.$"

PalletTown_RivalsHouse_Text_ExplainTownMap::
    .string "Ankapt'k KJIKANN L'SK'J\n"
    .string "we'jitoq pilei kjikann, kisna\l"
    .string "kekina'masit kjikann wisunn.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
    .string "DAISY: Nkutei l'nu,\n"
    .string "POKéMON nimajit.\p"
    .string "Ta'n nekmow kispniet,\n"
    .string "atlasmu'latl.$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
    .string "Meski'k l'sk'j KANTO um'tki.\n"
    .string "Uktapsunik!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
	.string "Wajuiknetek POKéMON\n"
	.string "kekina'matimkewei.$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
    .string "DAISY: Kwe', {PLAYER}!\n"
    .string "Naqsipkisink.\p"
    .string "Wikumul, epa'sit.\p"
    .string "O, katu, kilewewei\n"
    .string "POKéMON emekwamuksit.\p"
    .string "Pewalit pankwenatl newt?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
    .string "Mutt pankwenk?\n"
    .string "Oke', p'teweie'maiek.$"

PalletTown_RivalsHouse_Text_GroomWhichOne::
    .string "Teken newt pankwenk?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
    .string "DAISY: Oke', ne'tma'sit!\n"
    .string "Jaqalilukwet!$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
#ifdef BUGFIX @ The localizers missed what should be a textcolor change in the localizations.
    .string "{COLOR DARK_GRAY}{STR_VAR_1} jajikamuksit…\p"
    .string "{COLOR RED}DAISY: Ala! Kaqalukwei.\n"
#else @ In the JP games, gender-based text used a different font instead of different colors.
    .string "{FONT_NORMAL}{STR_VAR_1} jajikamuksit…\p"
    .string "{FONT_FEMALE}DAISY: Ala! Kaqalukwei.\n"
#endif
    .string "Wikwasamu'k?\p"
    .string "Weskewei…\n"
    .string "Wikwasamuksit POKéMON.$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
    .string "O, meskei'. Mutt pakwenk\n"
    .string "WA'W, melujioqo.$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
    .string "DAISY: Kilewewei POKéMON kesalatl\n"
    .string "Ta'n tlipkije'k ankweiwatl kesalatl.\p"
    .string "For example, {PLAYER}, may I see\n"
    .string "your first POKéMON?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
    .string "It couldn't possibly love you\n"
    .string "any more than it does now.\p"
    .string "Your POKéMON is happy beyond\n"
    .string "words.$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
    .string "It looks very happy.\p"
    .string "I wish {RIVAL} could see this and\n"
    .string "learn something from it.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly::
    .string "It's quite friendly with you.\n"
    .string "Keep being good to it!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
    .string "It's warming up to you.\n"
    .string "Trust must be growing between you.$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
    .string "It's not quite familiar with you\n"
    .string "yet.\p"
    .string "POKéMON are all quite wary when\n"
    .string "you first get them.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
    .string "{PLAYER}, I don't like the way it\n"
    .string "glares at you.\p"
    .string "Could you try being a little nicer\n"
    .string "to it?$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
    .string "…Um, it's not easy for me to say\n"
    .string "this, but…\p"
    .string "Is there some reason why your\n"
    .string "POKéMON would hate you so much?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
    .string "“Esmatmuksit aq sekkw\n"
    .string "CLEFAIRY”$"

