@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "Wajuiknetek POKéMON\n"
	.string "kekina'matimkewei.$"

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap::
	.string "KJIKANN L'SK'J.$"

Text_PokeMartShelf::
	.string "W'o!\n"
	.string "Te'sit POKéMON papitaqann!$"

Text_DishesPlatesNeatlyLinedUp::
	.string "Eptaqann esma'tekl.$"

Text_Kitchen::
	.string "Welima'q!\n"
	.string "Na'tuen etloqsatl.$"

Text_Dresser::
	.string "Uksuateja'taqann welaptm.\n"
	.string "Ewe'ke'kik.$"

Text_Snacks::
	.string "Nana'n mawamk'tekl.$"

Text_PokemartSign::
	.string "Papitaqann ms't tami!\n"
	.string "POKéMON MAKASAN$"

Text_PokecenterSign::
	.string "Nepilatl ki'lewei POKéMON!\n"
	.string "POKéMON KSNUKO'KUOM$"

Text_Indigo_UltimateGoal::
	.string "INDIGO PLATEAU\p"
	.string "The ultimate goal of TRAINERS!\n"
	.string "POKéMON LEAGUE HQ$"

Text_Indigo_HighestAuthority::
	.string "INDIGO PLATEAU\p"
	.string "The highest POKéMON authority!\n"
	.string "POKéMON LEAGUE HQ$"

Text_Food::
	.string "It should be packed with all kinds\n"
	.string "of delicious things to eat.$"

Text_Blueprints::
	.string "It's a blueprint of some sort.\n"
	.string "It's filled with diagrams and text.$"

Text_Painting::
	.string "It's a pretty picture of a POKéMON.\n"
	.string "It looks like it's feeling good.$"

Text_PowerPlantMachine::
	.string "Koqwei net mulin?\n"
	.string "Mutt maliapt'k!$"

Text_Telephone::
	.string "It's a telephone.\n"
	.string "Better not use it.$"

Text_Computer::
	.string "It's all complicated words and\n"
	.string "numbers that make no sense…$"

Text_AdvertisingPoster::
	.string "It's an advertising poster about\n"
	.string "all kinds of products.$"

Text_TastyFood::
	.string "O, that smells tasty!\n"
	.string "It might get the stomach growling!$"

Text_TrashBin::
	.string "Inside this…\n"
	.string "……\p"
	.string "There's nothing here!$"

Text_Cup::
	.string "It's a cup with a POKéMON mark\n"
	.string "on it.$"

Text_PolishedWindow::
	.string "The window is very well polished.$"

Text_BeautifulSkyWindow::
	.string "Outside the window…\p"
	.string "The sky looks fantastically\n"
	.string "beautiful.$"

Text_BlinkingLights::
	.string "Pitiatek milamu'kl\n"
	.string "wasoqotesink.$"

Text_NeatlyLinedUpTools::
	.string "All sorts of tools are lined up\n"
	.string "neatly.$"

Text_ImpressiveMachine::
	.string "It's a machine of some sort.\n"
	.string "It sure is impressive.$"

Text_VideoGame::
	.string "It's the latest video game!\n"
	.string "It sure looks fun!$"

Text_Burglary::
	.string "There are obvious signs of burglary\n"
	.string "here…$"

Text_PlayerFacingTVScreen::
	.string "Ki'l nemiatl newt POKéMON!\n"
	.string "Teleiaq kise'k.$"
