gOtherText_NewName::
    .string "PILEI WISUN$" 

gNameChoice_Green::
    .string "ESKIT$" 

gNameChoice_Red::
    .string "MEKWE'K$" 

gNameChoice_Leaf::
    .string "NIPI$" 

gNameChoice_Fire::
    .string "PUKTEW$" 

gNameChoice_Gary::
    .string "TUMA$"

gNameChoice_Kaz::
    .string "KAZ$"

gNameChoice_Toru::
    .string "TORU$"

gNameChoice_Ash::
    .string "AQAMOQ$"

gNameChoice_Kene::
    .string "KENE$"

gNameChoice_Geki::
    .string "GEKI$"

gNameChoice_Jak::
    .string "JAK$"

gNameChoice_Janne::
    .string "JANNE$"

gNameChoice_Jonn::
    .string "JONN$"

gNameChoice_Kamon::
    .string "KAMON$"

gNameChoice_Karl::
    .string "KARL$"

gNameChoice_Taylor::
    .string "TAYLOR$"

gNameChoice_Oscar::
    .string "OSCAR$"

gNameChoice_Hiro::
    .string "HIRO$"

gNameChoice_Max::
    .string "MAX$"

gNameChoice_Jon::
    .string "JON$"

gNameChoice_Ralph::
    .string "RALPH$"

gNameChoice_Kay::
    .string "KAY$"

gNameChoice_Tosh::
    .string "TOSH$"

gNameChoice_Roak::
    .string "ROAK$"

gNameChoice_Omi::
    .string "OMI$"

gNameChoice_Jodi::
    .string "JODI$"

gNameChoice_Amanda::
    .string "AMANDA$"

gNameChoice_Hillary::
    .string "HILLARY$"

gNameChoice_Makey::
    .string "MAKEY$"

gNameChoice_Michi::
    .string "MICHI$"

gNameChoice_Paula::
    .string "NE'TATA$"

gNameChoice_June::
    .string "JUNE$"

gNameChoice_Cassie::
    .string "CASSIE$"

gNameChoice_Rey::
    .string "FAE$"

gNameChoice_Seda::
    .string "SEDA$"

gNameChoice_Kiko::
    .string "KIKO$"

gNameChoice_Mina::
    .string "MINA$"

gNameChoice_Norie::
    .string "NORIE$"

gNameChoice_Sai::
    .string "SAI$"

gNameChoice_Momo::
    .string "MOMO$"

gNameChoice_Suzi::
    .string "SUZI$"

gControlsGuide_Text_Intro::
    .string "Kekina'mul te'sit pisoqos'ti'l espe'k$" 

gControlsGuide_Text_DPad::
    .string "Ukkwata'q.\n" 
    .string "Elk meknatl te'sit elqwanik.$"

gControlsGuide_Text_AButton::
    .string "Welte'tk ilsutk, pa'qawajeimatl,\n"
    .string "sespewo'kwet, aja'sit klusuaqann.$"

gControlsGuide_Text_BButton::
    .string "Wejitu'wet, moqwa' ilsutk,\n"
    .string "moqwa' newtnemi'k.$"

gControlsGuide_Text_StartButton::
    .string "Pana'latl elqwanik.$"

gControlsGuide_Text_SelectButton::
    .string "Aja'sit papitaqann aq e'watl\n"
    .string "papitaqan espe'k.$"

gControlsGuide_Text_LRButtons::
    .string "Iknmuetoq apoqonmati'l.$"

gOakSpeech_Text_AskPlayerGender::
    .string "K'il lpa'tuj kisna e'pite'ji'j?$"

gPikachuIntro_Text_Page1::
    .string "Uks'tqamu wejkwa'tiek,\n"
    .string "poqtamkita'ieg ta'n k'il nikanus.\n"
    .string "\n"
    .string "Keluatl l'nu aq pa'qawajeimatl\n"
    .string "ms't tami, kutann, awti'l,\n"
    .string "kisna elmaqei'l.\n"
    .string "Kekina'masultieg ms't koqwei.$"

gPikachuIntro_Text_Page2::
    .string "Pilei'k awti'jl pana's'k ta'n k'il\n"
    .string "mawitqo'tmu'tijik, wissuiknematl,\n"
    .string "aq pa'qawajeimatl.\n"
    .string "\n"
    .string "Jijuaqa, l'nu kaqamutuit k'il\n"
    .string "aq jujij kimteluit.\n"
    .string "Melkitoltiek, saputaqatmek!$"

gPikachuIntro_Text_Page3::
    .string "Through your adventure, we hope\n"
    .string "that you will interact with all sorts\n"
    .string "of people and achieve personal growth.\n"
    .string "That is our biggest objective.\n"
    .string "\n"
    .string "Press the A Button, and let your\n"
    .string "adventure begin!$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "Kwe'!\n"
    .string "Welta'si a's'kul!\p"
    .string "Pjila'si uks'tqamu POKéMON!\p"
    .string "Teluisi MIMKWAQAN.\p"
    .string "Piltu'wi't'k keknue'k\n"
    .string "POKéMON NUJIKINA'MUET.\p$"

gOakSpeech_Text_ThisWorld::
    .string "Uks'tqamu…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "…POKéMON wiaqqatmu'tijik na'te'l!$"

gOakSpeech_Text_IStudyPokemon::
    .string "For some people, POKéMON are pets.\n"
    .string "Others use them for battling.\p"
    .string "As for myself…\p"
    .string "I study POKéMON as a profession.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "But first, tell me a little about\n"
    .string "yourself.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "Let's begin with your name.\n"
    .string "What is it?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "Right…\n"
    .string "So your name is {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
    .string "This is my grandson.\p"
    .string "He's been your rival since you both\n"
    .string "were babies.\p"
    .string "…Erm, what was his name now?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "Your rival's name, what was it now?$"

gOakSpeech_Text_ConfirmRivalName::
    .string "…Er, was it {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
    .string "That's right! I remember now!\n"
    .string "His name is {RIVAL}!\p$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
    .string "Your very own POKéMON legend is\n"
    .string "about to unfold!\p"
    .string "A world of dreams and adventures\n"
    .string "with POKéMON awaits! Let's go!$"
