PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{RIVAL}: Koqwei, pas'k {PLAYER}?\n"
    .string "Nmijka moqwa' tet.$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "{RIVAL}: Nmijka!\n"
    .string "Siwieskmai!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "{RIVAL}: Kwe'! Nmijka! Alua'tu!\n"
    .string "Weja'tu elk, na to'q?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "{RIVAL}: Qeq, moqwa' pisoqqoweieksit\n"
    .string "nkutei ki'l. Kisikwei!\p"
    .string "Nikana'sit aq meknatl, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "{RIVAL}: Ketapjat'l'k, etna!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "{RIVAL} mesnatl {STR_VAR_1}\n"
    .string "MIMKWAN!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "{RIVAL}: Welamuksultiek\n"
    .string "ajiglu'sultiek ki'l.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "{RIVAL}: Eskmat, {PLAYER}!\n"
    .string "Ankaptmek nineiwei POKéMON!\p"
    .string "Kaqamutul!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "KOQWEI?\n"
    .string "Mekt'k!\l"
    .string "Mekn'k o'pla'teket POKéMON!$"

@ Also used for early Route 22 battle
Text_RivalVictory::
    .string "{RIVAL}: E'e!\n"
    .string "Wikwasapewit, na to'q?$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "{RIVAL}: Etna! ilsutekei ni'newei\n"
    .string "POKéMON matnk aq melqa'toq!\p"
    .string "{PLAYER}! Nmijka!\n"
    .string "Pe'l ap ta'n tujiw!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{RIVAL}: Nmijka!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{RIVAL}: Suel awanta'si!\n"
    .string "Koqwei ukjit k'il wikumatl?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{RIVAL}: Ketloqo, nmijka!\n"
    .string "Eptoqatk ni'n!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "{PLAYER}, maskeltm teluei, katu\n"
    .string "moqwa' wetmite'lmul.\p"
    .string "Nenk! ukkwe'ji'jl KJIKANN L'SK'J\n"
    .string "maqatuit!\p"
    .string "Telimk moqwa' maqatu'atl ki'l,\n"
    .string "{PLAYER}! Qaqaqa!\p"
    .string "Mutt ikowaqana'latl nekm\n"
    .string "mala elmi'knik!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "MIMKWAN: {RIVAL}?\n"
    .string "Sankewi ankita'sit…\p"
    .string "Na to'q, telimul\n"
    .string "wejku'et! Eskmat!\p"
    .string "Ula, {PLAYER}.\p"
    .string "Si'sk POKéMON tet.\p"
    .string "Qaqa!\p"
    .string "POKéMON pitek weket\n"
    .string "POKé TU'QANN.\p"
    .string "Wejkwa'tekemk, n'in\n"
    .string "espe'k POKéMON NIKANUS.\p"
    .string "Nike', kaqi'siskekipunai,\n"
    .string "kekkunatl pas'k si'sk.\p"
    .string "Iknumuatl ne'wt.\n"
    .string "Lie tmk! Meknatl!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "MIMKWAN: Kiskajiet, {RIVAL}.\n"
    .string "Kisi meknatl elk!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "MIMKWAN: Nike', {PLAYER}.\p"
    .string "Si'st POKé TU'QANN\n"
    .string "kekkunatl POKéMON pitek.\p"
    .string "Teken ki'l meknatl?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "MIMKWAN: Kwe'!\n"
    .string "Mutt ejikla'timk!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "Ah! CHARMANDER is your choice.\n"
    .string "You should raise it patiently.\p"
    .string "So, {PLAYER}, you're claiming the\n"
    .string "FIRE POKéMON CHARMANDER?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "Hm! SQUIRTLE is your choice.\n"
    .string "It's one worth raising.\p"
    .string "So, {PLAYER}, you've decided on the\n"
    .string "WATER POKéMON SQUIRTLE?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "I see! BULBASAUR is your choice.\n"
    .string "It's very easy to raise.\p"
    .string "So, {PLAYER}, you want to go with\n"
    .string "the GRASS POKéMON BULBASAUR?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "This POKéMON is really quite\n"
    .string "energetic!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "{PLAYER} received the {STR_VAR_1}\n"
    .string "from PROF. MIMKWAN!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "MIMKWAN: If a wild POKéMON appears,\n"
    .string "your POKéMON can battle it.\p"
    .string "With it at your side, you should be\n"
    .string "able to reach the next town.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "MIMKWAN: {PLAYER}, raise your young\n"
    .string "POKéMON by making it battle.\p"
    .string "It has to battle for it to grow.$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "MIMKWAN: Oh, {PLAYER}!\n"
    .string "How is my old POKéMON?\p"
    .string "Well, it seems to be growing more\n"
    .string "attached to you.\p"
    .string "You must be talented as a POKéMON\n"
    .string "TRAINER.\p"
    .string "Koqwei?\n"
    .string "You have something for me?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER} nutateji'putoq\n"
    .string "MIMKWAN MAWPILAQAN.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "Aq! \n"
    .string "Kekinue'k POKé TU'QAN!\p"
    .string "Natkiteket.\n"
    .string "Wela'lin!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "MIMKWAN: Na to'q!\n"
    .string "Etamul kitk.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "Wetmo'taqan kisi'k epa'suatk\n"
    .string "ni'newei pataw'ti. Telui'tm POKéDEX!\p"
    .string "It automatically ewi'k'k data on\n"
    .string "POKéMON you've seen or caught.\p"
    .string "It's a high-tech encyclopedia!$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "MIMKWAN: {PLAYER} aq {RIVAL}.\n"
    .string "Take these with you.$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "{PLAYER} mesn'k POKéDEX\n"
    .string "MIMKWAN.$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "MIMKWAN: You can't get detailed data\n"
    .string "on POKéMON by just seeing them.\p"
    .string "You must catch them to obtain\n"
    .string "complete data.\p"
    .string "So, here are some tools for\n"
    .string "catching wild POKéMON.$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "{PLAYER} mesn'k na'n POKé TU'AQANK.$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "When a wild POKéMON appears,\n"
    .string "it's fair game.\p"
    .string "Just throw a POKé BALL at it and\n"
    .string "try to catch it!\p"
    .string "This won't always work, however.\p"
    .string "A healthy POKéMON can escape.\n"
    .string "You have to be lucky!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "To make a complete guide on all\n"
    .string "the POKéMON in the world…\p"
    .string "That was my dream!\p"
    .string "But, I'm too old.\n"
    .string "I can't get the job done.\p"
    .string "So, I want you two to fulfill my\n"
    .string "dream for me.\p"
    .string "Get moving, you two.\p"
    .string "This is a great undertaking in\n"
    .string "POKéMON history!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "POKéMON around the world wait for\n"
    .string "you, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "Ah, {PLAYER}!\n"
    .string "How is your POKéDEX shaping up?\p"
    .string "{RIVAL} has already caught some\n"
    .string "POKéMON and added to the data.\p"
    .string "So, {PLAYER}, let's have a look at\n"
    .string "your POKéDEX.\p"
    .string "…What's the matter?\n"
    .string "You've added no new data at all.\p"
    .string "I'll give you these, so do try a\n"
    .string "little harder.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "MIMKWAN: Come see me sometime.\p"
    .string "After all, I want to know how your\n"
    .string "POKéDEX is coming along.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "It's like an encyclopedia, but the\n"
    .string "pages are blank.$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "Those are POKé BALLS.\n"
    .string "They contain POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "That's PROF. MIMKWAN's last POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "Esna'toq (START) pana'latl ELQWANIK!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "The EWI'K'K option is on ELQWANIK.\n"
    .string "Use it regularly.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "All POKéMON types have strong and\n"
    .string "weak points against others.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "There's an e-mail message here.\p"
    .string "…\p"
    .string "Finally!\n"
    .string "The ultimate TRAINERS of the\l"
    .string "POKéMON LEAGUE are ready to\l"
    .string "take on all comers!\p"
    .string "Bring your best POKéMON and see\n"
    .string "how you rate as a TRAINER!\p"
    .string "POKéMON LEAGUE HQ\n"
    .string "INDIGO PLATEAU\p"
    .string "PROF. MIMKWAN, please visit us!\n"
    .string "…$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "I study POKéMON as PROF. MIMKWAN's\n"
    .string "AIDE.$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "Hi, {PLAYER}. I bet you've become\n"
    .string "good friends with your POKéMON.\p"
    .string "By the way, did you know about\n"
    .string "DAISY?\p"
    .string "If you show DAISY your POKéMON,\n"
    .string "she can tell how much it likes you.\p"
    .string "Occasionally, she will even groom\n"
    .string "a POKéMON for you.\p"
    .string "This is a secret, so please don't\n"
    .string "tell anyone.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "PROF. MIMKWAN is going to have his own\n"
    .string "radio show soon.\p"
    .string "The program will be called PROF.\n"
    .string "MIMKWAN's POKéMON SEMINAR.$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "PROF. MIMKWAN may not look like much,\n"
    .string "but he's the authority on POKéMON.\p"
    .string "Many POKéMON TRAINERS hold him in\n"
    .string "high regard.$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "Ah, now this is excellent!\p"
    .string "{PLAYER}, I have another important\n"
    .string "favor to ask of you.\p"
    .string "I need you to listen closely.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "Recently, there have been sightings\n"
    .string "of many rare POKéMON species.\p"
    .string "I'm talking about POKéMON that\n"
    .string "have never been seen in KANTO.\p"
    .string "I would love to go see things for\n"
    .string "myself, but I'm much too old.\p"
    .string "Since I can't do it, {PLAYER}, I'd\n"
    .string "like you to go in my place.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{RIVAL}: Hey, I heard that!\p"
    .string "Gramps, what's with favoring\n"
    .string "{PLAYER} over me all the time?\p"
    .string "I went and collected more POKéMON,\n"
    .string "and faster, too.\p"
    .string "You should just let me handle\n"
    .string "everything.$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "MIMKWAN: I know, I know.\n"
    .string "Of course I need your help, too.\p"
    .string "Now, I need to see both your\n"
    .string "POKéDEXES.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "PROF. MIMKWAN took both POKéDEX\n"
    .string "units.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "…And that's done!\p"
    .string "Now these units can record data on\n"
    .string "a lot more POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "{PLAYER}'s POKéDEX was upgraded!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "Now, {PLAYER} and {RIVAL}!\p"
    .string "This time, you really must work\n"
    .string "towards filling your POKéDEXES.\p"
    .string "I urge you to make them the best\n"
    .string "and the most complete of all time!\p"
    .string "Truly, this is a monumentally great\n"
    .string "undertaking in POKéMON history!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{RIVAL}: Gramps, calm down.\n"
    .string "Don't get so excited.\p"
    .string "I'll get the POKéDEX completed,\n"
    .string "don't you worry about a thing.\p"
    .string "I think I'll try looking around\n"
    .string "ONE ISLAND first…\p"
    .string "Anyways, I'm outta here!$"

