PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{RIVAL}: Koqwei, pas'k {PLAYER}?\n"
    .string "NMIJKA moqwa' tet.$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "{RIVAL}: NMIJKA!\n"
    .string "Siwieskmai!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "{RIVAL}: Kwe'! NMIJKA! Alua'tu!\n"
    .string "Weja'tu elk, na to'q?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "{RIVAL}: Qeq, moqwa' pisoqqoweieksit\n"
    .string "nkutei ki'l. Kisikwei!\p"
    .string "Nikana'sit aq meknatl, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "{RIVAL}: Ketapjat'l'k, etna!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "{RIVAL} mesnatl {STR_VAR_1}.\n"
    .string "Wela'lin NMIJKA!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "{RIVAL}: Welamuksultiek\n"
    .string "ajiglu'sultiek ki'l.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "{RIVAL}: Eskmat, {PLAYER}!\n"
    .string "Ankaptmek nineiwei POKéMON!\p"
    .string "Kaqamutul!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "KOQWEI?\n"
    .string "Mekt'k!\l"
    .string "Mekn'k o'pla'teket POKéMON!$"

@ Also used for early Route 22 battle
Text_RivalVictory::
    .string "{RIVAL}: E'e!\n"
    .string "Wikwasapewit, na to'q?$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "{RIVAL}: Etna! ilsutekei ni'newei\n"
    .string "POKéMON matnk aq melqa'toq!\p"
    .string "{PLAYER}! NMIJKA!\n"
    .string "Pe'l ap ta'n tujiw!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{RIVAL}: NMIJKA!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{RIVAL}: Suel awanta'si!\n"
    .string "Koqwei ukjit k'il wikumatl?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{RIVAL}: Ketloqo, NMIJKA!\n"
    .string "Eptoqatk ni'n!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "{PLAYER}, maskeltm teluei, katu\n"
    .string "moqwa' wetmite'lmul.\p"
    .string "Nenk! ukkwe'ji'jl KJIKANN L'SK'J\n"
    .string "maqatuit!\p"
    .string "Telimk moqwa' maqatu'atl ki'l,\n"
    .string "{PLAYER}! Qaqaqa!\p"
    .string "Mutt ikowaqana'latl nekm\n"
    .string "mala elmi'knik!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "MIMKWAN: {RIVAL}?\n"
    .string "Sankewi ankita'sit…\p"
    .string "Na to'q, telimul\n"
    .string "wejku'et! Eskmat!\p"
    .string "Wla, {PLAYER}.\p"
    .string "Si'sk POKéMON tet.\p"
    .string "Qaqa!\p"
    .string "POKéMON pitek weket\n"
    .string "POKé TU'AQANK.\p"
    .string "Wejkwa'tekemk, n'in\n"
    .string "espe'k POKéMON NIKANUS.\p"
    .string "Nike', kaqi'siskekipunai,\n"
    .string "kekkunatl pas'k si'sk.\p"
    .string "Iknumuatl ne'wt.\n"
    .string "Lie tmk! Meknatl!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "MIMKWAN: Kiskajiet, {RIVAL}.\n"
    .string "Kisi meknatl elk!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "MIMKWAN: Nike', {PLAYER}.\p"
    .string "Si'st POKé TU'AQANK\n"
    .string "kekkunatl POKéMON pitek.\p"
    .string "Teken ki'l meknatl?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "MIMKWAN: Kwe'!\n"
    .string "Mutt ejikla'timk!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "Aq! Ki'l meknatl CHARMANDER.\n"
    .string "Kiskajiet ankweiwatl.\p"
    .string "{PLAYER}, ki'l meknatl\n"
    .string "PUKTEW POKéMON CHARMANDER?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "Qm! Ki'l meknatl SQUIRTLE.\n"
    .string "Telawtik ankweiwatl.\p"
    .string "{PLAYER}, ki'l meknatl\n"
    .string "SAMQWAN POKéMON SQUIRTLE?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "Nemitu! Ki'l meknatl BULBASAUR.\n"
    .string "Nqamasiatew ankweiwatl.\p"
    .string "{PLAYER}, ki'l meknatl\n"
    .string "MSIKU POKéMON BULBASAUR?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "Wla POKéMON ma'muniw\n"
    .string "nalakit!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "{PLAYER} mesnatl {STR_VAR_1}.\n"
    .string "Wela'lin MIMKWAN!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "MIMKWAN: Tliaq POKéMON waqasit neia'sit,\n"
    .string "ki'lewei POKéMON matnk.\p"
    .string "Upmetuk ki'l, tepiass\n"
    .string "tepnatl kjikan sk'mtuk.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "MIMKWAN: {PLAYER}, ankweiwatl\n"
    .string "POKéMON ilsuteket matnk.\p"
    .string "Amujpa matnk nikwet.$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "MIMKWAN: O, {PLAYER}!\n"
    .string "Me' tale'k ni'newei saqawei POKéMON?\p"
    .string "Teleiaq ajiaq kelpisit ki'l\p"
    .string "Ki'l mawintawo'tk POKéMON\n"
    .string "NIKANUS.\p"
    .string "Koqwei?\n"
    .string "Wesko'tk nat koqwei iknmu ni'n?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER} nutateji'putoq\n"
    .string "MIMKWAN MAWPILAQAN.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "Aq!\n"
    .string "Kekinue'k POKé TU'AQAN!\p"
    .string "Natkiteket.\n"
    .string "Wela'lin!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "MIMKWAN: Na to'q!\n"
    .string "Etamul kitk.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "Wetmo'taqan kisi'k epa'suatk\n"
    .string "ni'newei pataw'ti. Telui'tm POKéDEX!\p"
    .string "Ewi'k'k kina'matnewey atel POKéMON\n"
    .string "ki'l nemitekemk kisna welta'tl.\p"
    .string "Wi'katikn espe'k!$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "MIMKWAN: {PLAYER} aq {RIVAL}.\n"
    .string "Wesua'tumk wla.$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "{PLAYER} mesn'k POKéDEX.\n"
    .string "Wela'lin MIMKWAN!$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "MIMKWAN: Nutapukuet POKéMON\n"
    .string "nemiatl pas'k.\p"
    .string "Amujpa mesnatl nekmow\n"
    .string "weja'toq kina'masuti.\p"
    .string "Iknmaq wetmo'taqan\n"
    .string "mesnatl waqasit POKéMON.$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "{PLAYER} mesn'k na'n POKé TU'AQANK.$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "Ta'nuk waqasit POKéMON wejku'et,\n"
    .string "waltes iljo'qonk.\p"
    .string "POKé TU'AQAN elaqtoq aq\n"
    .string "mesnatl POKéMON!\p"
    .string "Mutt elukwek apjiw.\p"
    .string "Jajike'k POKéMON alsumukwat.\n"
    .string "Amujpa lokowit!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "Ewi'kikei kina'masuti m'st\n"
    .string "POKéMON peikwaqatk wksitqamuk…\p"
    .string "Pewai sa'q!\p"
    .string "Katu, kisiku'et.\n"
    .string "Ejela'teket.\p"
    .string "Pewalul ta'pu kaqa'toq\n"
    .string "ni'newei pewitaqan.\p"
    .string "Kaqawa'sit, k'il ta'pu.\p"
    .string "Espe'k lgowaqan\n"
    .string "POKéMON kina'masuti!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "POKéMON alapaqetl wksitqamuk\n"
    .string "eskmat ki'l, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "Aq, {PLAYER}!\n"
    .string "Ki'lewei POKéDEX aja'sit?\p"
    .string "{RIVAL} ki's mesnatl te's'k\n"
    .string "POKéMON aq ewi'k'k kina'masuti.\p"
    .string "Eta, {PLAYER}, ankaptm\n"
    .string "ki'lewei POKéDEX.\p"
    .string "…Tale'k?\n"
    .string "Ki'l mutt ewi'k'k kina'masuti.\p"
    .string "iknmul weket, kina'sit\n"
    .string "me' ijka.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "MIMKWAN: Emittukwet.\p"
    .string "Pewatm kaqikji'toq ki'lewei\n"
    .string "POKéDEX aja'sit.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "Staqa wi'katikn, katu sikue'k.$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "Wla POKé TU'AQANK.\n"
    .string "POKéMON pisit!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "Na MIMKWAN uktejkewei POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "Esna'toq (START) pana'latl ELQWANIK!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "EWI'K'K ELQWANIK.\n"
    .string "E'w'k kaqi'sk.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "Ms't POKéMON tapunemi'k melkiknat\n"
    .string "kisna menaqanat matnk iktikik.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "Aknutmaqan tet.\p"
    .string "…\p"
    .string "Klapis!\n"
    .string "Mujkajewei NIKANUSK wejiet\l"
    .string "POKéMON LEAGUE kiskat'pukuit!\p"
    .string "Pekisulatl kilewewei POKéMON\n"
    .string "mukjajewei aq esp'pukuit!\p"
    .string "POKéMON LEAGUE HQ\n"
    .string "NISQUNAMU'K ESPAQMIKEK\p"
    .string "MIMKWAN, emittukwalatl kinu!\n"
    .string "…$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "Kekina'masi POKéMON nkutei MIMKWAN.$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "Kwe', {PLAYER}. Amujpa eliatl\n"
    .string "POKéMON kilewewei oqote'tut.\p"
    .string "Elk, nenuatl DAISY?\p"
    .string "Ewsitutk DAISY kilewewei POKéMON,\n"
    .string "nekm aknutmuatl ta's'k kesalatl ki'l.\p"
    .string "Jijuaqa, nekm pankwenatl\n"
    .string "kilewewei POKéMON.\p"
    .string "Mutt a'tukwewatl me' wen.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "MIMKWAN poqtewo'kwet kne'k.\p"
    .string "Telui'tmek MIMKWAN\n"
    .string "POKéMON MAWIO'MI.$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "MIMKWAN etukjel amalaptmek,\n"
    .string "katu nekm alsusuti POKéMON.\p"
    .string "Te'sit POKéMON NIKANUSK\n"
    .string "nenuite'lmatl.$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "Aq, mawiklulk!\p"
    .string "{PLAYER}, etawaqtmat app\n"
    .string "iktik espe'k lkowaqan.\p"
    .string "Amujpa jiks'tuit.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "Kejikow, awije'jkl POKéMON\n"
    .string "wejkwimuska'sit.\p"
    .string "Aknimk POKéMON wla mutt\n"
    .string "nemiatl keskmniak asistek KANTO.\p"
    .string "Kesipuatm ketanatl,\n"
    .string "katu tetuje'i.\p"
    .string "Kiaspiw ni'n ejela'teket,\n"
    .string "{PLAYER}, kesipuatm ki'l ala'sit.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{RIVAL}: Kwe', metewenk!\p"
    .string "NMIJKA, tal kis piamiksalatl\n"
    .string "{PLAYER} piamiw ni'n apjiw?\p"
    .string "Meknk piamiw POKéMON,\n"
    .string "aq jaqala'tu, elk.\p"
    .string "Etuk pas'k iknmuatl ni'n\n"
    .string "kaqalatl ms't.$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "MIMKWAN: Nenm, nenm.\n"
    .string "Talma' menueko'l, elk.\p"
    .string "Nike', menuekei nemitoq kitk\n"
    .string "kilewewei POKéDEX.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "MIMKWAN wesua'toq kitk\n"
    .string "POKéDEX.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "…Kaqa'tekei!\p"
    .string "Nike' weket kisa'toq ewi'k'k\n"
    .string "me' kina'masuti POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "{PLAYER} POKéDEX ankua'toq!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "Nike', {PLAYER} aq {RIVAL}!\p"
    .string "Ketlewei, amujpa anku'lukwet\n"
    .string "kaqa'toq kilewewei POKéDEX.\p"
    .string "Amujpa eliatl mujkajewei\n"
    .string "aq pjili'w kina'masuti apjiw!\p"
    .string "Ketlewei, eta espe'k ikowaqan\n"
    .string "kina'matimk POKéMON!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{RIVAL}: NMIJKA, atlasmit.\n"
    .string "Mutt nenaqite'tk.\p"
    .string "Ni'n kaqa'toq POKéDEX,\n"
    .string "mutt sespete'tk wla.\p"
    .string "Angita'sit wejinmitoq asistek\n"
    .string "NEWT MENIKU tmk…\p"
    .string "Me' pa, maja'si!$"

