PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "KIJU': …Ketloqo.\n"
    .string "Ms't lpa'tuj naqt'k wikuaq.\l"
    .string "Na t'oq.\p"
    .string "O, e'e. MIMKWAQAN, a'se'k,\n"
    .string "alkwiluatl k'il.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "KIJU': …Ketloqo.\n"
    .string "Ms't girls dream of traveling.\l"
    .string "Na t'oq.\p"
    .string "O, e'e. MIMKWAQAN, a'se'k,\n"
    .string "alkwiluatl k'il.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "KIJU': {PLAYER}!\n"
    .string "Atlasmu'teket.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "KIJU': O, kelu'lk! Ki'l aq ki'lewei\n"
    .string "POKéMON welap'tk.\l"
    .string "Atiu nike'!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "K'il nemitoq a'tukwaqan.\n"
    .string "Ne'w lpa'tujk ukkwataq\l"
    .string "a'sistek puljainawti.\p"
    .string "…Niktua'l'k elk.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "K'il nemitoq a'tukwaqan.\n"
    .string "E'pite'ji'j enmisa'tkwatp'tesink\l"
    .string "a'sistek awti etlseknk.\p"
    .string "…Niktua'l'k elk.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Quq, keska't…$"

