PalletTown_Text_OakDontGoOut::
    .string "MIMKWAN: Kwe'! Eskipa'tl!\n"
    .string "Mutt tewiet!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "MIMKWAN: An'stawtek!\n"
    .string "Wakasit POKéMON weskowa'sit\p"
    .string "pita'q msiku! Nuta't POKéMON ukjit\n"
    .string "ki'lewei ikatk.\p"
    .string "Geitu!\n"
    .string "Apaja'sit!$"

PalletTown_Text_RaisingMonsToo::
    .string "Anko'tm POKéMON, elk.\p"
    .string "Ta'nuk nekmow melqa'toq,\n"
    .string "ikalatl ni'n.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "Pu'taliewe'l piltui!\p"
    .string "Ika'toq aq mawo'toqol\n"
    .string "papitaqan aq POKéMON pitek.$"

PalletTown_Text_OakPokemonResearchLab::
    .string "MIMKWAN POKéMON KINA'MUO'KUOM$"

PalletTown_Text_PlayersHouse::
    .string "{PLAYER} apsi'kan$"

PalletTown_Text_RivalsHouse::
    .string "{RIVAL} apsi'kan$"

PalletTown_Text_TownSign::
    .string "WALQWAN KJIKAN\n"
    .string "Nipetekmu'tiek milamu'kl!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "MIMKWAN: O, {PLAYER}!\n"
    .string "Ki'l apaja'sit?\p"
    .string "Ta'sit k'il ewi'k'k ki'lewei\n"
    .string "POKéDEX?\p"
    .string "Nemi'k?\p"
    .string "Nemituek…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "Ki'l mesnatl {STR_VAR_2}…\p"
    .string "Qm, amalapt'k…\n"
    .string "Ki'l kina'sit katu.\p"
    .string "Ta'n ki'l ewi'k'k me' ijka,\n"
    .string "ewsitutk, wela'latl.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "Ki'l mesnatl… {STR_VAR_2}!?\n"
    .string "Nike', jiltek!\p"
    .string "Pewalk pipanimatl ki'l,\n"
    .string "{PLAYER}.\p"
    .string "Wejku'et.\n"
    .string "Poqtukkwalatl.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "MIMKWAN: Kwe', {PLAYER}!\n"
    .string "Ki'l teleiaq kesatk ukkwata'q.\p"
    .string "Kaqikjij'k ki'l, {PLAYER},\n"
    .string "milita'si ki'l poqtamka'sit\l"
    .string "te'sit um'tkiwal mna'q keitmk.\p"
    .string "Mawiklu'sit, mawiklu'sit!\n"
    .string "Qoqoqo.$"

