PalletTown_Text_OakDontGoOut::
    .string "MIMKWAQAN: Kwe'! Eskipa'tl!\n"
    .string "Mutt tewiet!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "MIMKWAQAN: An'stawtek!\n"
    .string "Wakasit POKéMON weskowa'sit\p"
    .string "pita'q msiku! Nuta't POKéMON ukjit\n"
    .string "ki'lewei ikatk.\p"
    .string "Geitu!\n"
    .string "Apaja'sit!$"

PalletTown_Text_RaisingMonsToo::
    .string "Anko'tm POKéMON, elk.\p"
    .string "Ta'nuk nekmow melqa'toq,\n"
    .string "ikalatl ni'n.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "Munti'l incredible!\p"
    .string "You can now store and recall items\n"
    .string "and POKéMON as data via PC.$"

PalletTown_Text_OakPokemonResearchLab::
    .string "MIMKWAQAN POKéMON KINA'MUO'KUOM$"

PalletTown_Text_PlayersHouse::
    .string "{PLAYER}'s apsi'kan$"

PalletTown_Text_RivalsHouse::
    .string "{RIVAL}'s apsi'kan$"

PalletTown_Text_TownSign::
    .string "WALQWAN KJIKAN\n"
    .string "Nipetekmu'tiek milamu'kl!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "MIMKWAQAN: O, {PLAYER}!\n"
    .string "You're back, are you?\p"
    .string "How much have you filled in your\n"
    .string "POKéDEX?\p"
    .string "May I see it?\p"
    .string "Let's see…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "You've caught {STR_VAR_2}…\p"
    .string "Hm, it looks as if you're putting\n"
    .string "in an honest effort.\p"
    .string "When you manage to fill it some\n"
    .string "more, come show me, please.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "You've caught… {STR_VAR_2}!?\n"
    .string "Now, this is impressive!\p"
    .string "There's something I wanted to ask\n"
    .string "of you, {PLAYER}.\p"
    .string "Come.\n"
    .string "Follow me.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "MIMKWAQAN: Kwe', {PLAYER}!\n"
    .string "You seem to be enjoying traveling.\p"
    .string "Knowing you, {PLAYER}, I can easily\n"
    .string "imagine you going out to even more\l"
    .string "exotic locales.\p"
    .string "Good for you, good for you.\n"
    .string "Qoqoqo.$"

